// AUTO-GENERATED by tools/generate-dinner-rush-levels.js — do not hand-edit.
// Source recipes: tools/curated-recipes.json (from Fannie Farmer's The Boston
// Cooking-School Cook Book, 1896, public domain, Project Gutenberg #65061).
// Regenerate with: node tools/generate-dinner-rush-levels.js > games/dinner-rush/levels-data.js
(function (root) {
  root.DINNER_RUSH_LEVELS = [
  {
    "id": "stage-1",
    "name": "Stage 1: Fritter Beans",
    "recipeName": "Fritter Beans",
    "ingredients": [
      "Egg",
      "Milk",
      "Salt"
    ],
    "decoys": [
      "Shredded pineapple",
      "Grated pineapple"
    ],
    "steps": [
      "Beat egg until light, add milk, salt, and flour",
      "Put through colander or pastry tube into deep fat, and fry until brown; drain on brown paper"
    ]
  },
  {
    "id": "stage-2",
    "name": "Stage 2: Strawberry Sauce",
    "recipeName": "Strawberry Sauce",
    "ingredients": [
      "Butter",
      "Strawberries",
      "Powdered sugar"
    ],
    "decoys": [
      "Paprika",
      "Egg"
    ],
    "steps": [
      "Cream the butter, add sugar gradually, egg beaten until stiff, and strawberries",
      "Beat until fruit is mashed"
    ]
  },
  {
    "id": "stage-3",
    "name": "Stage 3: Cranberry Frappé",
    "recipeName": "Cranberry Frappé",
    "ingredients": [
      "Cranberries",
      "Water",
      "Sugar"
    ],
    "decoys": [
      "Lobster",
      "Chopped parsley"
    ],
    "steps": [
      "Cook cranberries and water eight minutes; then force through a sieve",
      "Add sugar and lemon juice, and freeze to a mush, using equal parts of ice and salt"
    ]
  },
  {
    "id": "stage-4",
    "name": "Stage 4: Covington Cream",
    "recipeName": "Covington Cream",
    "ingredients": [
      "Sugar",
      "Formosa tea infusion",
      "Rum"
    ],
    "decoys": [
      "Apricots",
      "Green Coloring"
    ],
    "steps": [
      "Mix ingredients, and freeze to a mush",
      "Serve in frappé glasses"
    ]
  },
  {
    "id": "stage-5",
    "name": "Stage 5: Chestnut Croquettes",
    "recipeName": "Chestnut Croquettes",
    "ingredients": [
      "Mashed French chestnuts",
      "Thick cream",
      "Egg yolks",
      "Sugar"
    ],
    "decoys": [
      "Orange juice and pulp",
      "Orange juice"
    ],
    "steps": [
      "Mix ingredients in order given",
      "Shape in balls, dip in crumbs, egg, and crumbs again, fry in deep fat, and drain"
    ]
  },
  {
    "id": "stage-6",
    "name": "Stage 6: Custard Soufflé",
    "recipeName": "Custard Soufflé",
    "ingredients": [
      "Butter",
      "Flour",
      "Scalded milk",
      "Eggs"
    ],
    "decoys": [
      "Yvette Cordial",
      "Figs, finely chopped"
    ],
    "steps": [
      "Melt butter, add flour, and gradually hot milk; when well thickened, pour on to yolks of eggs beaten until thick and lemon-colored, and mixed with sugar; cool, and cut and fold in whites of eggs beaten stiff and dry",
      "Turn into buttered pudding-dish, and bake from thirty to thirty-five minutes in slow oven; take from oven and serve at once,—if not served immediately it is sure to fall; serve with Creamy or Foamy Sauce"
    ]
  },
  {
    "id": "stage-7",
    "name": "Stage 7: Blueberry Pie",
    "recipeName": "Blueberry Pie",
    "ingredients": [
      "Berries",
      "Flour",
      "Sugar"
    ],
    "decoys": [
      "Potatoes",
      "Rye flour"
    ],
    "steps": [
      "Line a deep plate with Plain Paste, fill with berries slightly dredged with flour; sprinkle with sugar and salt, cover, and bake forty-five to fifty minutes in a moderate oven",
      "For sweetening, some prefer to use one-third molasses, the remaining two-thirds to be sugar",
      "Six green grapes (from which seeds have been removed) cut in small pieces much improve the flavor, particularly where huckleberries are used in place of blueberries"
    ]
  },
  {
    "id": "stage-8",
    "name": "Stage 8: Chocolate Filling",
    "recipeName": "Chocolate Filling",
    "ingredients": [
      "Squares chocolate",
      "Powdered sugar",
      "Milk",
      "Egg yolks"
    ],
    "decoys": [
      "Yvette Cordial",
      "Egg whites"
    ],
    "steps": [
      "Melt chocolate over hot water, add one-half the sugar, and milk; add remaining sugar, and yolk of egg; then cook in double boiler until it thickens, stirring constantly at first, that mixture may be perfectly smooth",
      "Cool slightly, flavor, and spread"
    ]
  },
  {
    "id": "stage-9",
    "name": "Stage 9: Gelatine Frosting",
    "recipeName": "Gelatine Frosting",
    "ingredients": [
      "Boiling water",
      "Granulated gelatine",
      "Confectioners’ sugar"
    ],
    "decoys": [
      "Washed figs",
      "Dried split peas"
    ],
    "steps": [
      "Dissolve gelatine in boiling water",
      "Add sugar and flavoring and beat until of right consistency to spread",
      "Crease in squares when slightly hardened"
    ]
  },
  {
    "id": "stage-10",
    "name": "Stage 10: Twin Mountain Muffins",
    "recipeName": "Twin Mountain Muffins",
    "ingredients": [
      "Butter",
      "Sugar",
      "Egg",
      "Milk",
      "Flour"
    ],
    "decoys": [
      "Yellow ginger",
      "Cayenne",
      "Chopped lobster meat"
    ],
    "steps": [
      "Cream the butter; add sugar and egg well beaten; sift baking powder with flour, and add to the first mixture, alternating with milk",
      "Bake in buttered tin gem pans twenty-five minutes"
    ]
  },
  {
    "id": "stage-11",
    "name": "Stage 11: Cereal with Fruit",
    "recipeName": "Cereal with Fruit",
    "ingredients": [
      "Wheat Germ",
      "Cold water",
      "Boiling water",
      "Salt"
    ],
    "decoys": [
      "Bottles ginger ale",
      "Granulated gelatin",
      "Sweet cider"
    ],
    "steps": [
      "Mix cereal, salt, and cold water; add to boiling water placed on front of range",
      "Boil five minutes, steam in double boiler thirty minutes; stir in dates, and serve with cream",
      "To serve for breakfast, or as a simple dessert"
    ]
  },
  {
    "id": "stage-12",
    "name": "Stage 12: Scrambled Eggs",
    "recipeName": "Scrambled Eggs",
    "ingredients": [
      "Eggs",
      "Milk",
      "Salt",
      "Pepper"
    ],
    "decoys": [
      "Pounded macaroons",
      "Figs, finely chopped",
      "Rind one lemon"
    ],
    "steps": [
      "Beat eggs slightly with silver fork; add salt, pepper, and milk",
      "Heat omelet pan, put in butter, and when melted, turn in the mixture",
      "Cook until of creamy consistency, stirring and scraping from bottom of the pan"
    ]
  },
  {
    "id": "stage-13",
    "name": "Stage 13: Salmon Soup",
    "recipeName": "Salmon Soup",
    "ingredients": [
      "Salmon",
      "Scalded milk",
      "Butter",
      "Flour",
      "Salt"
    ],
    "decoys": [
      "Blade of mace",
      "Salt and pepper",
      "Carrot"
    ],
    "steps": [
      "Drain oil from salmon, remove skin and bones, rub through a sieve",
      "Add gradually the milk, season, and bind"
    ]
  },
  {
    "id": "stage-14",
    "name": "Stage 14: Soubise Sauce",
    "recipeName": "Soubise Sauce",
    "ingredients": [
      "Sliced onions",
      "Velouté Sauce",
      "Cream or milk"
    ],
    "decoys": [
      "Celery",
      "Crab meat",
      "Egg well beaten"
    ],
    "steps": [
      "Cover onions with boiling water, cook five minutes, drain, again cover with boiling water, and cook until soft; drain, and rub through a sieve",
      "Add to sauce with cream",
      "Season with salt and pepper",
      "Serve with mutton, pork chops, or “hard-boiled” eggs"
    ]
  },
  {
    "id": "stage-15",
    "name": "Stage 15: Tartar Sauce",
    "recipeName": "Tartar Sauce",
    "ingredients": [
      "Vinegar",
      "Lemon juice",
      "Salt",
      "Worcestershire Sauce",
      "Butter"
    ],
    "decoys": [
      "Shredded cocoanut",
      "Porto Rico molasses",
      "Square melted chocolate"
    ],
    "steps": [
      "Mix vinegar, lemon juice, salt, and Worcestershire Sauce in a small bowl, and heat over hot water",
      "Brown the butter in an omelet pan, and strain into first mixture"
    ]
  },
  {
    "id": "stage-16",
    "name": "Stage 16: Swedish Timbales",
    "recipeName": "Swedish Timbales",
    "ingredients": [
      "Flour",
      "Salt",
      "Sugar",
      "Milk",
      "Egg"
    ],
    "decoys": [
      "Baking power",
      "Finely chopped onion",
      "Popped corn"
    ],
    "steps": [
      "Mix dry ingredients, add milk gradually, and beaten egg; then add olive oil",
      "Shape, using a hot timbale iron, fry in deep fat until crisp and brown; take from iron and invert on brown paper to drain"
    ]
  },
  {
    "id": "stage-17",
    "name": "Stage 17: Peach Tapioca",
    "recipeName": "Peach Tapioca",
    "ingredients": [
      "Peaches",
      "Powdered sugar",
      "Tapioca",
      "Boiling water",
      "Sugar"
    ],
    "decoys": [
      "Pounded cardamon seeds",
      "Washed figs",
      "Vinegar"
    ],
    "steps": [
      "Drain peaches, sprinkle with powdered sugar, and let stand one hour; soak tapioca one hour in cold water to cover; to peach syrup add enough boiling water to make three cups; heat to boiling-point, add tapioca drained from cold water, sugar, and salt; then cook in a double boiler until transparent",
      "Line a mould or pudding-dish with peaches cut in quarters, fill with tapioca, and bake in moderate oven thirty minutes; cool slightly, turn on a dish, and serve with Cream Sauce I"
    ]
  },
  {
    "id": "stage-18",
    "name": "Stage 18: Brandy Sauce",
    "recipeName": "Brandy Sauce",
    "ingredients": [
      "Butter",
      "Powdered sugar",
      "Brandy",
      "Egg yolks",
      "Egg whites"
    ],
    "decoys": [
      "Pounded cardamon seeds",
      "Granulated gelatine",
      "Cold water"
    ],
    "steps": [
      "Cream the butter, add sugar gradually, then brandy very slowly, well beaten yolks, and milk or cream",
      "Cook over hot water until it thickens as a custard, pour on to beaten whites"
    ]
  },
  {
    "id": "stage-19",
    "name": "Stage 19: Lemon Jelly",
    "recipeName": "Lemon Jelly",
    "ingredients": [
      "Box gelatine or",
      "Granulated gelatine",
      "Cold water",
      "Boiling water",
      "Sugar"
    ],
    "decoys": [
      "Grated rind  orange",
      "Milk, scalded",
      "Almond extract"
    ],
    "steps": [
      "Soak gelatine twenty minutes in cold water, dissolve in boiling water, strain, and add to sugar and lemon juice",
      "Turn into mould, and chill"
    ]
  },
  {
    "id": "stage-20",
    "name": "Stage 20: Pomona Frappé",
    "recipeName": "Pomona Frappé",
    "ingredients": [
      "Sugar",
      "Water",
      "Sweet cider",
      "Orange juice"
    ],
    "decoys": [
      "Powdered sugar",
      "Vanilla",
      "Worcestershire Sauce"
    ],
    "steps": [
      "Make a syrup by boiling sugar and water twenty minutes",
      "Add cider, orange juice, and lemon juice",
      "Cool, strain, and freeze to a mush"
    ]
  },
  {
    "id": "stage-21",
    "name": "Stage 21: Angel Parfait",
    "recipeName": "Angel Parfait",
    "ingredients": [
      "Sugar",
      "Water",
      "Egg whites",
      "Heavy cream"
    ],
    "decoys": [
      "Formosa tea infusion",
      "Beef extract",
      "Crab meat"
    ],
    "steps": [
      "Boil sugar and water until syrup will thread when dropped from tip of spoon",
      "Pour slowly on the beaten whites of eggs, and continue the beating until mixture is cool",
      "Add cream beaten until stiff, and vanilla; then freeze"
    ]
  },
  {
    "id": "stage-22",
    "name": "Stage 22: Iced Madeira Sauce",
    "recipeName": "Iced Madeira Sauce",
    "ingredients": [
      "Orange juice",
      "Lemon juice",
      "Madeira wine",
      "Sugar",
      "Boiling water"
    ],
    "decoys": [
      "Shredded pineapple",
      "Cream of tartar",
      "Buttered crumbs"
    ],
    "steps": [
      "Freeze fruit juice and wine; boil sugar and water, pour on slowly to beaten whites of eggs, set in pan of salted ice-water, and stir until cold",
      "Add to frozen mixture"
    ]
  },
  {
    "id": "stage-23",
    "name": "Stage 23: Boston Favorite Cake",
    "recipeName": "Boston Favorite Cake",
    "ingredients": [
      "Butter",
      "Sugar",
      "Eggs",
      "Milk",
      "Flour"
    ],
    "decoys": [
      "Cold water",
      "Parsley",
      "Peppercorns"
    ],
    "steps": [
      "Cream the butter, add sugar gradually, eggs beaten until light, then milk and flour mixed and sifted with baking powder",
      "This recipe makes two loaves, or one-half the mixture may be baked in individual tins"
    ]
  },
  {
    "id": "stage-24",
    "name": "Stage 24: Butter Scotch",
    "recipeName": "Butter Scotch",
    "ingredients": [
      "Sugar",
      "Molasses",
      "Vinegar",
      "Boiling water"
    ],
    "decoys": [
      "Egg whites",
      "Chopped walnut meats",
      "Lemon juice"
    ],
    "steps": [
      "Boil ingredients together until, when tried in cold water, mixture will become brittle",
      "Turn into a well buttered pan; when slightly cool, mark with a sharp-pointed knife in squares",
      "This candy is much improved by cooking a small piece of vanilla bean with other ingredients"
    ]
  },
  {
    "id": "stage-25",
    "name": "Stage 25: Fig Cups",
    "recipeName": "Fig Cups",
    "ingredients": [
      "Washed figs",
      "Chopped salted almonds",
      "Sugar",
      "Lemon juice"
    ],
    "decoys": [
      "Sliced onions",
      "Yeast cakes",
      "Bananas sliced"
    ],
    "steps": [
      "Stuff figs with almonds",
      "Put sugar, lemon juice, and wine in chafing-dish; when heated, add figs, cover, and cook until figs are tender, turning and basting often",
      "Serve with Lady Fingers"
    ]
  },
  {
    "id": "stage-26",
    "name": "Stage 26: Third Bread",
    "recipeName": "Third Bread",
    "ingredients": [
      "Lukewarm water",
      "Yeast cake",
      "Salt",
      "Molasses",
      "Rye flour",
      "Granulated corn meal"
    ],
    "decoys": [
      "Egg whites",
      "Water",
      "Shredded cocoanut",
      "Cinnamon"
    ],
    "steps": [
      "Dissolve yeast cake in water, add remaining ingredients, and mix thoroughly",
      "Let rise, shape, let rise again, and bake as Entire Wheat Bread"
    ]
  },
  {
    "id": "stage-27",
    "name": "Stage 27: Waffles",
    "recipeName": "Waffles",
    "ingredients": [
      "Flour",
      "Baking powder",
      "Salt",
      "Milk",
      "Egg yolks",
      "Egg whites"
    ],
    "decoys": [
      "Milk or Chicken Stock",
      "Corn",
      "Granulated corn meal",
      "Ice"
    ],
    "steps": [
      "Mix and sift dry ingredients; add milk gradually, yolks of eggs well beaten, butter, and whites of eggs beaten stiff; cook on a greased hot waffle-iron",
      "Serve with maple syrup"
    ]
  },
  {
    "id": "stage-28",
    "name": "Stage 28: Oyster Stuffing",
    "recipeName": "Oyster Stuffing",
    "ingredients": [
      "Cracker crumbs",
      "Melted butter",
      "Salt",
      "Pepper",
      "Lemon juice",
      "Finely chopped parsley"
    ],
    "decoys": [
      "Bay leaf",
      "Rye flour",
      "Smoked dried beef",
      "Formosa tea infusion"
    ],
    "steps": [
      "Add seasonings and butter to cracker crumbs",
      "Clean oysters, and remove tough muscles; add soft parts to mixture, with two tablespoons oyster liquor to moisten"
    ]
  },
  {
    "id": "stage-29",
    "name": "Stage 29: Rice Sauce",
    "recipeName": "Rice Sauce",
    "ingredients": [
      "Rice",
      "Milk",
      "Onion",
      "Cloves",
      "Butter"
    ],
    "decoys": [
      "Box gelatine or",
      "Lemon",
      "Cinnamon",
      "Ice"
    ],
    "steps": [
      "Wash rice, add to milk, and cook in double boiler until soft",
      "Rub through a fine strainer, return to double boiler, add onion stuck with cloves, and cook fifteen minutes",
      "Remove onion, add butter, salt, and pepper"
    ]
  },
  {
    "id": "stage-30",
    "name": "Stage 30: Farina Cakes with Jelly",
    "recipeName": "Farina Cakes with Jelly",
    "ingredients": [
      "Scalded milk",
      "Farina",
      "Sugar",
      "Salt"
    ],
    "decoys": [
      "Dried lima beans",
      "Hot water",
      "Pounded macaroons",
      "Junket Tablets"
    ],
    "steps": [
      "Mix farina, sugar, and salt, add to milk, and cook in double boiler twenty minutes, stirring constantly until mixture has thickened",
      "Add egg slightly beaten, pour into a buttered shallow pan, and brush over with one egg slightly beaten and diluted with one tablespoon milk",
      "Brown in a moderate oven",
      "Cut in squares, and serve with a cube of jelly on each square"
    ]
  },
  {
    "id": "stage-31",
    "name": "Stage 31: Crab meat, Indienne",
    "recipeName": "Crab meat, Indienne",
    "ingredients": [
      "Butter",
      "Finely chopped onion",
      "Flour",
      "Curry powder",
      "Chicken stock",
      "Crab meat"
    ],
    "decoys": [
      "Mustard",
      "Grated mild cheese",
      "Baking power",
      "Mocha coffee"
    ],
    "steps": [
      "Cook butter with onion three minutes, add flour mixed with curry powder and chicken stock",
      "When boiling-point is reached add crab meat and season with salt"
    ]
  },
  {
    "id": "stage-32",
    "name": "Stage 32: Cottage Pudding",
    "recipeName": "Cottage Pudding",
    "ingredients": [
      "Butter",
      "Sugar",
      "Egg",
      "Milk",
      "Flour",
      "Baking powder"
    ],
    "decoys": [
      "Vanilla or",
      "Ginger",
      "Sliced apples",
      "Finely chopped onion"
    ],
    "steps": [
      "Cream the butter, add sugar gradually, and egg well beaten; mix and sift flour, baking powder, and salt; add alternately with milk to first mixture; turn into buttered cake pan; bake thirty-five minutes",
      "Serve with Vanilla or Hard Sauce"
    ]
  },
  {
    "id": "stage-33",
    "name": "Stage 33: Coffee Custard",
    "recipeName": "Coffee Custard",
    "ingredients": [
      "Milk",
      "Ground coffee",
      "Eggs",
      "Sugar",
      "Salt"
    ],
    "decoys": [
      "Tomatoes",
      "Orange juice",
      "Brown Stock",
      "Vanilla or"
    ],
    "steps": [
      "Scald milk with coffee, and strain",
      "Beat eggs slightly; add sugar, salt, vanilla, and milk",
      "Strain into buttered individual moulds, set in pan of hot water, and bake until firm"
    ]
  },
  {
    "id": "stage-34",
    "name": "Stage 34: Apricot Sorbet",
    "recipeName": "Apricot Sorbet",
    "ingredients": [
      "Apricots",
      "Sugar",
      "Wine",
      "Lemon juice"
    ],
    "decoys": [
      "Granulated gelatin",
      "Grated pineapple",
      "Canton ginger",
      "Vinegar"
    ],
    "steps": [
      "Drain apricots, and add to syrup the pulp rubbed through a sieve",
      "Add sugar, wine, and lemon juice",
      "Freeze to a mush, then fold in the whip obtained from cream",
      "Let stand one and one-half hours, and serve in glasses"
    ]
  },
  {
    "id": "stage-35",
    "name": "Stage 35: Frozen Tom and Jerry",
    "recipeName": "Frozen Tom and Jerry",
    "ingredients": [
      "Milk",
      "Sugar",
      "Egg yolks",
      "Salt",
      "Cream",
      "Rum"
    ],
    "decoys": [
      "Warm wheat mush",
      "Vanilla",
      "Lukewarm water",
      "Strawberries"
    ],
    "steps": [
      "Make a custard of first four ingredients; strain, cool, add cream, and freeze to a mush",
      "Add rum and brandy, and finish the freezing"
    ]
  },
  {
    "id": "stage-36",
    "name": "Stage 36: Marshmallow Paste",
    "recipeName": "Marshmallow Paste",
    "ingredients": [
      "Sugar",
      "Milk",
      "Marshmallows",
      "Hot water"
    ],
    "decoys": [
      "French chestnuts",
      "Paprika",
      "Few grains pepper",
      "White Stock"
    ],
    "steps": [
      "Put sugar and milk in a saucepan, heat slowly to boiling-point without stirring, and boil six minutes",
      "Break marshmallows in pieces and melt in double boiler, add hot water, and cook until mixture is smooth, then add hot syrup gradually, stirring constantly",
      "Beat until cool enough to spread, then add vanilla",
      "This may be used for both filling and frosting"
    ]
  },
  {
    "id": "stage-37",
    "name": "Stage 37: Cheese Omelet",
    "recipeName": "Cheese Omelet",
    "ingredients": [
      "Eggs",
      "Melted butter",
      "Salt",
      "Few grains cayenne"
    ],
    "decoys": [
      "Thin cream",
      "Shredded almonds",
      "Cloves",
      "Macaroni"
    ],
    "steps": [
      "Beat eggs slightly, add one-half teaspoon melted butter, salt, cayenne, and cheese",
      "Melt remaining butter, add mixture, and cook until firm, without stirring",
      "Roll, and sprinkle with grated cheese",
      "Serve with Graham bread sandwiches"
    ]
  },
  {
    "id": "stage-38",
    "name": "Stage 38: Raised Muffins",
    "recipeName": "Raised Muffins",
    "ingredients": [
      "Scalded milk",
      "Boiling water",
      "Butter",
      "Sugar",
      "Salt",
      "Yeast cake",
      "Egg"
    ],
    "decoys": [
      "Squares chocolate",
      "Scallops",
      "Mocha coffee",
      "Fine oatmeal"
    ],
    "steps": [
      "Add butter, sugar, and salt to milk and water; when lukewarm, add yeast cake, and when dissolved, egg well beaten, and flour; beat thoroughly, cover, and let rise over night",
      "In morning, fill buttered muffin rings two-thirds full; let rise until rings are full, and bake thirty minutes in hot oven"
    ]
  },
  {
    "id": "stage-39",
    "name": "Stage 39: Imperial Muffins",
    "recipeName": "Imperial Muffins",
    "ingredients": [
      "Scalded milk",
      "Sugar",
      "Salt",
      "Flour",
      "Corn meal",
      "Butter"
    ],
    "decoys": [
      "Highly seasoned",
      "Milk, scalded",
      "Square melted chocolate",
      "Rye meal"
    ],
    "steps": [
      "Add sugar and salt to milk; when lukewarm add dissolved yeast cake, and one and one-fourth cups flour",
      "Cover, and let rise until light, then add corn meal, remaining flour, and butter",
      "Let rise over night; in the morning fill buttered muffin rings two-thirds full; let rise until rings are full and bake thirty minutes in hot oven"
    ]
  },
  {
    "id": "stage-40",
    "name": "Stage 40: Rye Gems",
    "recipeName": "Rye Gems",
    "ingredients": [
      "Rye flour",
      "Flour",
      "Baking powder",
      "Salt",
      "Molasses",
      "Milk",
      "Eggs"
    ],
    "decoys": [
      "Tapioca",
      "Hominy",
      "Egg whites",
      "Coffee infusion"
    ],
    "steps": [
      "Mix and sift dry ingredients, add molasses, milk, eggs well beaten, and butter",
      "Bake in hot oven in buttered gem pans twenty-five minutes"
    ]
  },
  {
    "id": "stage-41",
    "name": "Stage 41: Fried Drop Cakes",
    "recipeName": "Fried Drop Cakes",
    "ingredients": [
      "Flour",
      "Baking powder",
      "Salt",
      "Sugar",
      "Milk",
      "Egg"
    ],
    "decoys": [
      "Few grains pepper",
      "Tapioca",
      "Fine stale bread crumbs",
      "Potatoes"
    ],
    "steps": [
      "Beat egg until light; add milk, dry ingredients mixed and sifted, and melted butter",
      "Drop by spoonfuls in hot, new, deep fat; fry until light brown and cooked through, which must at first be determined by piercing with a skewer, or breaking apart",
      "Remove with a skimmer, and drain on brown paper"
    ]
  },
  {
    "id": "stage-42",
    "name": "Stage 42: Kornlet Soup",
    "recipeName": "Kornlet Soup",
    "ingredients": [
      "Kornlet",
      "Cold water",
      "Milk, scalded",
      "Butter",
      "Chopped onion",
      "Flour",
      "Salt"
    ],
    "decoys": [
      "Warm wheat mush",
      "Sweet cider",
      "Few grains salt",
      "Pearl or Minute Tapioca"
    ],
    "steps": [
      "Cook kornlet in cold water twenty minutes; rub through a sieve, and add milk",
      "Fry butter and onion three minutes; remove onion, add flour, salt, and pepper, and stir into boiling soup"
    ]
  },
  {
    "id": "stage-43",
    "name": "Stage 43: Yorkshire Pudding",
    "recipeName": "Yorkshire Pudding",
    "ingredients": [
      "Milk",
      "Flour",
      "Eggs",
      "Salt"
    ],
    "decoys": [
      "Parsley",
      "Chestnut purée",
      "White corn meal",
      "Thin cream",
      "Small potatoes"
    ],
    "steps": [
      "Mix salt and flour, and add milk gradually to form a smooth paste; then add eggs beaten until very light",
      "Cover bottom of hot pan with some of beef fat tried out from roast, pour mixture in pan one-half inch deep",
      "Bake twenty minutes in hot oven, basting after well risen, with some of the fat from pan in which meat is roasting",
      "Cut in squares for serving",
      "Bake, if preferred, in greased, hissing hot iron gem pans"
    ]
  },
  {
    "id": "stage-44",
    "name": "Stage 44: Oyster Sauce",
    "recipeName": "Oyster Sauce",
    "ingredients": [
      "Oysters",
      "Butter",
      "Flour",
      "Milk or Chicken Stock",
      "Salt",
      "Pepper"
    ],
    "decoys": [
      "Cold water",
      "Shredded almonds",
      "Finely chopped parsley",
      "Lobster",
      "Fine stale bread crumbs"
    ],
    "steps": [
      "Wash oysters, reserve liquor, heat, strain, add oysters, and cook until plump",
      "Remove oysters, and make a sauce of butter, flour, oyster liquor, and milk",
      "Add oysters, and season with salt and pepper"
    ]
  },
  {
    "id": "stage-45",
    "name": "Stage 45: Devilled Scallops",
    "recipeName": "Devilled Scallops",
    "ingredients": [
      "Scallops",
      "Butter",
      "Made mustard",
      "Salt",
      "Few grains cayenne"
    ],
    "decoys": [
      "Vanilla or",
      "Wheat Germ",
      "Chopped lobster meat",
      "Oranges",
      "Dried lima beans"
    ],
    "steps": [
      "Clean scallops, drain, and heat to the boiling-point; drain again, and reserve liquor",
      "Cream the butter, add mustard, salt, cayenne, two-thirds cup reserved liquor, and scallops chopped",
      "Let stand one-half hour",
      "Put in a baking-dish, cover with crumbs, and bake twenty minutes"
    ]
  },
  {
    "id": "stage-46",
    "name": "Stage 46: Apple Tapioca",
    "recipeName": "Apple Tapioca",
    "ingredients": [
      "Pearl or Minute Tapioca",
      "Cold water",
      "Boiling water",
      "Salt",
      "Sour apples"
    ],
    "decoys": [
      "Egg, well beaten",
      "Small bunch violets",
      "Chestnut purée",
      "Beef extract",
      "Molasses"
    ],
    "steps": [
      "Soak tapioca one hour in cold water to cover, drain, add boiling water and salt; cook in double boiler until transparent",
      "Core and pare apples, arrange in buttered pudding-dish, fill cavities with sugar, pour over tapioca, and bake in moderate oven until apples are soft",
      "Serve with sugar and cream or Cream Sauce I",
      "Minute Tapioca requires no soaking"
    ]
  },
  {
    "id": "stage-47",
    "name": "Stage 47: Ginger Pudding",
    "recipeName": "Ginger Pudding",
    "ingredients": [
      "Butter",
      "Sugar",
      "Egg",
      "Flour",
      "Baking powder",
      "Salt",
      "Ginger"
    ],
    "decoys": [
      "Yeast cake",
      "Grated nutmeg",
      "Fine stale bread crumbs",
      "Parsley",
      "Onions"
    ],
    "steps": [
      "Cream the butter, add sugar gradually, and egg well beaten; mix and sift dry ingredients; add alternately with milk to first mixture",
      "Turn into buttered mould, cover, and steam two hours; serve with Vanilla Sauce"
    ]
  },
  {
    "id": "stage-48",
    "name": "Stage 48: Caramel Custard",
    "recipeName": "Caramel Custard",
    "ingredients": [
      "Scalded milk",
      "Eggs",
      "Salt",
      "Vanilla"
    ],
    "decoys": [
      "Terrapin",
      "Salmon",
      "Heavy cream",
      "Carrot",
      "Farina"
    ],
    "steps": [
      "Put sugar in omelet pan, stir constantly over hot part of range until melted to a syrup of light brown color",
      "Add gradually to milk, being careful that milk does not bubble up and go over, as is liable on account of high temperature of sugar",
      "As soon as sugar is melted in milk, add mixture gradually to eggs slightly beaten; add salt and flavoring, then strain in buttered mould",
      "Bake as custard",
      "Chill, and serve with Caramel Sauce"
    ]
  },
  {
    "id": "stage-49",
    "name": "Stage 49: Coffee Soufflé",
    "recipeName": "Coffee Soufflé",
    "ingredients": [
      "Coffee infusion",
      "Milk",
      "Sugar",
      "Salt",
      "Eggs",
      "Vanilla"
    ],
    "decoys": [
      "Vinegar",
      "Farina",
      "Small bunch violets",
      "Worcestershire Sauce",
      "Cold boiled halibut"
    ],
    "steps": [
      "Mix coffee infusion, milk, one-half of the sugar and gelatine, and heat in double boiler",
      "Add remaining sugar, salt, and yolks of eggs slightly beaten; cook until mixture thickens, remove from range, add whites of eggs beaten until stiff and vanilla",
      "Mould, chill, and serve with cream"
    ]
  },
  {
    "id": "stage-50",
    "name": "Stage 50: Praline Ice Cream",
    "recipeName": "Praline Ice Cream",
    "ingredients": [
      "Cream",
      "Sugar",
      "Jordan almonds",
      "Salt"
    ],
    "decoys": [
      "Thyme",
      "Mace",
      "Mixed mustard",
      "Potatoes",
      "Cold boiled halibut"
    ],
    "steps": [
      "Blanch almonds cut in pieces crosswise, and bake in a shallow pan until well browned, shaking pan frequently; then finely chop",
      "Caramelize one-half of the sugar, and add slowly to two cups of the cream scalded",
      "As soon as sugar is melted, add nuts, remaining sugar, and salt",
      "Cool, add remaining cream, and freeze",
      "A few grains salt is always an improvement to any ice cream mixture"
    ]
  },
  {
    "id": "stage-51",
    "name": "Stage 51: Strawberry Mousse",
    "recipeName": "Strawberry Mousse",
    "ingredients": [
      "Thin cream",
      "Box strawberries",
      "Sugar",
      "Box gelatine (scant) or",
      "Granulated gelatine",
      "Cold water"
    ],
    "decoys": [
      "Grated nutmeg",
      "Soft butter",
      "Farina",
      "Macaroni",
      "Chestnut purée"
    ],
    "steps": [
      "Wash and hull berries, sprinkle with sugar, and let stand one hour; mash, and rub through a fine sieve; add gelatine soaked in cold and dissolved in boiling water",
      "Set in pan of ice-water and stir until it begins to thicken; then fold in whip from cream, put in mould, cover, pack in salt and ice, and let stand four hours",
      "Raspberries may be used in place of strawberries"
    ]
  },
  {
    "id": "stage-52",
    "name": "Stage 52: Soft Sugar Gingerbread",
    "recipeName": "Soft Sugar Gingerbread",
    "ingredients": [
      "Eggs",
      "Sugar",
      "Flour",
      "Baking powder",
      "Salt",
      "Ginger"
    ],
    "decoys": [
      "Mustard",
      "Mashed French chestnuts",
      "Shredded almonds",
      "Extract lemon or",
      "Shortening"
    ],
    "steps": [
      "Beat eggs until light, and add sugar gradually",
      "Mix and sift dry ingredients, and add alternately with cream to first mixture",
      "Turn into a buttered cake pan, and bake thirty minutes in a moderate oven"
    ]
  },
  {
    "id": "stage-53",
    "name": "Stage 53: Oatmeal Cookies",
    "recipeName": "Oatmeal Cookies",
    "ingredients": [
      "Egg",
      "Sugar",
      "Thin cream",
      "Milk",
      "Fine oatmeal",
      "Flour",
      "Baking powder"
    ],
    "decoys": [
      "Sweet cider",
      "Vanilla",
      "Finely chopped parsley",
      "Chestnut purée",
      "Squares chocolate"
    ],
    "steps": [
      "Beat egg until light, add sugar, cream, and milk; then add oatmeal, flour, baking powder, and salt, mixed and sifted",
      "Toss on a floured board, roll, cut in shape, and bake in a moderate oven"
    ]
  },
  {
    "id": "stage-54",
    "name": "Stage 54: One Egg Cake",
    "recipeName": "One Egg Cake",
    "ingredients": [
      "Butter",
      "Sugar",
      "Egg",
      "Milk",
      "Flour"
    ],
    "decoys": [
      "Made mustard",
      "Pounded cardamon seeds",
      "Blade of mace",
      "Confectioners’ sugar",
      "Pearl or Minute Tapioca"
    ],
    "steps": [
      "Cream the butter, add sugar gradually, and egg well beaten",
      "Mix and sift flour and baking powder, add alternately with milk to first mixture",
      "Bake thirty minutes in a shallow pan",
      "Spread with Chocolate Frosting"
    ]
  },
  {
    "id": "stage-55",
    "name": "Stage 55: Cup Cakes",
    "recipeName": "Cup Cakes",
    "ingredients": [
      "Butter",
      "Sugar",
      "Eggs",
      "Milk",
      "Flour",
      "Baking powder"
    ],
    "decoys": [
      "Molasses",
      "Heavy cream",
      "Cold flaked salmon",
      "Mustard",
      "Salt and pepper"
    ],
    "steps": [
      "Put butter and sugar in a bowl, and stir until well mixed; add eggs well beaten, then milk, and flour mixed and sifted with baking powder and mace",
      "Bake in individual tins",
      "Cover with Chocolate Frosting"
    ]
  },
  {
    "id": "stage-56",
    "name": "Stage 56: Pound Cake",
    "recipeName": "Pound Cake",
    "ingredients": [
      "Butter",
      "Sugar",
      "Egg yolks",
      "Egg whites",
      "Flour",
      "Mace"
    ],
    "decoys": [
      "Squares chocolate",
      "Granulated corn meal",
      "Chopped parsley",
      "Buttered crumbs",
      "Baker’s chocolate"
    ],
    "steps": [
      "Cream the butter, add sugar gradually, and continue beating; then add yolks of eggs beaten until thick and lemon-colored, whites of eggs beaten until stiff and dry, flour, mace, and brandy",
      "Beat vigorously five minutes",
      "Bake in a deep pan one and one-fourth hours in a slow oven; or if to be used for fancy ornamented cakes, bake thirty to thirty-five minutes in a dripping-pan"
    ]
  },
  {
    "id": "stage-57",
    "name": "Stage 57: Orange Filling",
    "recipeName": "Orange Filling",
    "ingredients": [
      "Sugar",
      "Flour",
      "Grated rind  orange",
      "Orange juice",
      "Lemon juice",
      "Egg slightly beaten"
    ],
    "decoys": [
      "Corn",
      "Rolled Oats",
      "Yeast cake dissolved in",
      "Squares chocolate",
      "Popped corn"
    ],
    "steps": [
      "Mix ingredients in order given",
      "Cook ten minutes in double boiler, stirring constantly",
      "Cool before spreading"
    ]
  },
  {
    "id": "stage-58",
    "name": "Stage 58: Chocolate Cream Candy",
    "recipeName": "Chocolate Cream Candy",
    "ingredients": [
      "Sugar",
      "Milk",
      "Butter",
      "Squares chocolate"
    ],
    "decoys": [
      "Velouté Sauce",
      "Kumquat juice",
      "Canton ginger",
      "Heavy cream",
      "Salt and paprika"
    ],
    "steps": [
      "Put butter into granite saucepan; when melted, add sugar and milk",
      "Heat to boiling-point; then add chocolate, and stir constantly until chocolate is melted",
      "Boil thirteen minutes, remove from fire, add vanilla, and beat until creamy and mixture begins to sugar slightly around edge of saucepan",
      "Pour at once into a buttered pan, cool slightly, and mark in squares",
      "Omit vanilla, if desired, and add, while cooking, one-fourth teaspoon cinnamon"
    ]
  },
  {
    "id": "stage-59",
    "name": "Stage 59: Rolled Oats Bread",
    "recipeName": "Rolled Oats Bread",
    "ingredients": [
      "Boiling water",
      "Molasses",
      "Salt",
      "Butter",
      "Yeast cake dissolved in",
      "Lukewarm water",
      "Rolled Oats"
    ],
    "decoys": [
      "Almond extract",
      "Thick cream",
      "Whites two eggs",
      "Confectioners’ sugar",
      "Fine stale bread crumbs",
      "Chopped mushrooms"
    ],
    "steps": [
      "Add boiling water to oats and let stand one hour; add molasses, salt, butter, dissolved yeast cake, and flour; let rise, beat thoroughly, turn into buttered bread pans, let rise again, and bake",
      "By using one-half cup less flour, the dough is better suited for biscuits, but, being soft, is difficult to handle",
      "To make shaping of biscuits easy, take up mixture by spoonfuls, drop into plate of flour, and have palms of hands well covered with flour before attempting to shape"
    ]
  },
  {
    "id": "stage-60",
    "name": "Stage 60: Raised Oatmeal Muffins",
    "recipeName": "Raised Oatmeal Muffins",
    "ingredients": [
      "Scalded milk",
      "Sugar",
      "Salt",
      "Yeast cake dissolved in",
      "Lukewarm milk",
      "Cold cooked oatmeal"
    ],
    "decoys": [
      "Sugar or",
      "Yolks of eggs",
      "Cream of tartar",
      "Carrot",
      "Chopped cooked mutton",
      "Terrapin"
    ],
    "steps": [
      "Add sugar and salt to scalded milk; when lukewarm, add dissolved yeast cake",
      "Work oatmeal into flour with tips of fingers, and add to first mixture; beat thoroughly, cover, and let rise over night",
      "In morning, fill buttered iron gem pans two-thirds full, let rise on back of range that pan may gradually heat and mixture rise to fill pan",
      "Bake in moderate oven twenty-five to thirty minutes"
    ]
  },
  {
    "id": "stage-61",
    "name": "Stage 61: Cream Scones",
    "recipeName": "Cream Scones",
    "ingredients": [
      "Flour",
      "Baking power",
      "Sugar",
      "Salt",
      "Butter",
      "Eggs"
    ],
    "decoys": [
      "Vanilla or",
      "Brown Stock",
      "Anchovy essence",
      "Yeast cake",
      "Salt and pepper",
      "Mustard"
    ],
    "steps": [
      "Mix and sift together flour, baking powder, sugar, and salt",
      "Rub in butter with tips of fingers; add eggs well beaten, and cream",
      "Toss on a floured board, pat, and roll to three-fourths inch in thickness",
      "Cut in squares, brush with white of egg, sprinkle with sugar, and bake in a hot oven fifteen minutes"
    ]
  },
  {
    "id": "stage-62",
    "name": "Stage 62: White Corn Cake",
    "recipeName": "White Corn Cake",
    "ingredients": [
      "Butter",
      "Sugar",
      "Milk",
      "Egg whites",
      "White corn meal",
      "Flour",
      "Baking powder"
    ],
    "decoys": [
      "Scalded milk",
      "Eggs",
      "Finely chopped chives",
      "Whites two eggs",
      "Yolks of eggs",
      "Heavy cream"
    ],
    "steps": [
      "Cream the butter; add sugar gradually; add milk, alternating with dry ingredients, mixed and sifted",
      "Beat thoroughly; add whites of eggs beaten stiff",
      "Bake in buttered cake pan thirty minutes"
    ]
  },
  {
    "id": "stage-63",
    "name": "Stage 63: Rich Omelet",
    "recipeName": "Rich Omelet",
    "ingredients": [
      "Flour",
      "Salt",
      "Milk",
      "Eggs",
      "Butter"
    ],
    "decoys": [
      "Cold cooked oatmeal",
      "Sliced onions",
      "Milk, scalded",
      "Hot liquid",
      "Tomatoes or",
      "Egg yolks"
    ],
    "steps": [
      "Mix salt and flour, and add gradually milk",
      "Beat eggs until thick and lemon-colored, then add to first mixture",
      "Heat iron frying-pan and put in two-thirds of the butter; when butter is melted, pour in mixture",
      "As it cooks, lift with a griddle-cake turner so that uncooked part may run underneath; add remaining butter as needed, and continue lifting the cooked part until it is firm throughout",
      "Place on hotter part of range to brown; roll, and turn on hot platter"
    ]
  },
  {
    "id": "stage-64",
    "name": "Stage 64: Scalloped Lobster",
    "recipeName": "Scalloped Lobster",
    "ingredients": [
      "Lobster",
      "White Sauce II",
      "Salt",
      "Few grains cayenne"
    ],
    "decoys": [
      "Maraschino",
      "Junket Tablets",
      "Few grains salt",
      "Mustard",
      "Squash",
      "Pearl or Minute Tapioca"
    ],
    "steps": [
      "Remove lobster meat from shell and cut in cubes",
      "Heat in White Sauce and add seasonings",
      "Refill lobster shells, cover with buttered crumbs, and bake until crumbs are brown",
      "To prevent lobster shells from curling over lobster while baking, insert small wooden skewers of sufficient length to keep shell in its original shape",
      "To assist in preserving color of shell, brush over with olive oil before putting into oven",
      "Scalloped lobster may be baked in buttered scallop shells, or in a buttered baking-dish"
    ]
  },
  {
    "id": "stage-65",
    "name": "Stage 65: Tomato Cream Sauce",
    "recipeName": "Tomato Cream Sauce",
    "ingredients": [
      "Tomatoes",
      "Thyme",
      "Celery",
      "Onion",
      "Bay leaf",
      "White Sauce I",
      "Salt",
      "Few grains cayenne"
    ],
    "decoys": [
      "Mace",
      "Baking power",
      "Warm cooked hominy",
      "Chicken",
      "Canton ginger",
      "Fresh stewed tomatoes"
    ],
    "steps": [
      "Cook tomatoes twenty minutes with seasonings; rub through a strainer, add soda, then White Sauce",
      "Serve with Baked Fish or Lobster Cutlets"
    ]
  },
  {
    "id": "stage-66",
    "name": "Stage 66: Clam Fritters",
    "recipeName": "Clam Fritters",
    "ingredients": [
      "Clams",
      "Eggs",
      "Milk",
      "Flour",
      "Baking powder",
      "Salt"
    ],
    "decoys": [
      "Corn",
      "Sour milk",
      "Yvette Cordial",
      "Gelatine or",
      "Chicken",
      "Sherry or Madeira wine"
    ],
    "steps": [
      "Clean clams, drain from their liquor, and chop",
      "Beat eggs until light, add milk and flour mixed and sifted with baking powder, then add chopped clams, and season highly with salt and pepper",
      "Drop by spoonfuls, and fry in deep fat",
      "Drain on brown paper, and serve at once on a folded napkin"
    ]
  },
  {
    "id": "stage-67",
    "name": "Stage 67: Bread Pudding",
    "recipeName": "Bread Pudding",
    "ingredients": [
      "Stale bread crumbs",
      "Scalded milk",
      "Sugar",
      "Melted butter",
      "Eggs",
      "Salt",
      "Vanilla or"
    ],
    "decoys": [
      "Canton ginger",
      "Corn meal",
      "Chopped salted almonds",
      "Finely chopped parsley",
      "Onions",
      "Sour milk"
    ],
    "steps": [
      "Soak bread crumbs in milk, set aside until cool; add sugar, butter, eggs slightly beaten, salt, and flavoring; bake one hour in buttered pudding-dish in slow oven; serve with Vanilla Sauce",
      "In preparing bread crumbs for puddings avoid using outside crusts",
      "With a coarse grater there need be but little waste"
    ]
  },
  {
    "id": "stage-68",
    "name": "Stage 68: Graham Pudding",
    "recipeName": "Graham Pudding",
    "ingredients": [
      "Butter",
      "Molasses",
      "Milk",
      "Egg",
      "Graham flour",
      "Soda",
      "Salt"
    ],
    "decoys": [
      "Few grains salt",
      "Smoked dried beef",
      "Few grains cinnamon",
      "Chestnut purée",
      "Made mustard",
      "Washed figs"
    ],
    "steps": [
      "Melt butter, add molasses, milk, egg well beaten, dry ingredients mixed and sifted, and raisins; turn into buttered mould, cover, and steam two and one-half hours",
      "Serve with Wine Sauce",
      "Dates or figs cut in small pieces may be used in place of raisins"
    ]
  },
  {
    "id": "stage-69",
    "name": "Stage 69: Ivory Cream",
    "recipeName": "Ivory Cream",
    "ingredients": [
      "Granulated gelatine",
      "Cold water",
      "Boiling water",
      "Cream",
      "Powdered sugar"
    ],
    "decoys": [
      "Celery salt",
      "Cinnamon",
      "Cloves",
      "Corn meal",
      "Stale bread crumbs",
      "Apricots"
    ],
    "steps": [
      "Soak gelatine in cold water, dissolve in boiling water, and add sugar and wine",
      "Strain into a bowl, set in pan of ice-water, and beat until mixture thickens slightly",
      "Add to mixture whip from cream, and beat until mixture is thick enough to hold its shape",
      "Mould and chill",
      "Garnish with Sauterne Jelly"
    ]
  },
  {
    "id": "stage-70",
    "name": "Stage 70: Fig Ice Cream",
    "recipeName": "Fig Ice Cream",
    "ingredients": [
      "Milk",
      "Sugar",
      "Egg yolks",
      "Salt",
      "Figs, finely chopped",
      "Heavy cream",
      "Egg whites",
      "Vanilla"
    ],
    "decoys": [
      "Grated pineapple",
      "Madeira wine",
      "Arrowroot",
      "Tumbler currant jelly",
      "Yvette Cordial",
      "Finely chopped onion"
    ],
    "steps": [
      "Make custard of yolks of eggs, sugar, and milk; strain, add figs, cool, and flavor",
      "Add whites of eggs beaten until stiff and heavy cream beaten until stiff; freeze and mould"
    ]
  },
  {
    "id": "stage-71",
    "name": "Stage 71: Prune Pie",
    "recipeName": "Prune Pie",
    "ingredients": [
      "Prunes",
      "Sugar",
      "Lemon juice",
      "Butter"
    ],
    "decoys": [
      "Anchovy essence",
      "Large flat white turnip",
      "Peaches",
      "Yeast cake",
      "Yellow ginger",
      "Warm wheat mush"
    ],
    "steps": [
      "Wash prunes and soak in enough cold water to cover",
      "Cook in same water until soft",
      "Remove stones, cut prunes in quarters, and mix with sugar and lemon juice",
      "Reduce liquor to one and one-half tablespoons",
      "Line plate with paste, cover with prunes, pour over liquor, dot over with butter, and dredge with flour",
      "Put on an upper crust and bake in a moderate oven"
    ]
  },
  {
    "id": "stage-72",
    "name": "Stage 72: Scottish Fancies",
    "recipeName": "Scottish Fancies",
    "ingredients": [
      "Egg",
      "Sugar",
      "Melted butter",
      "Rolled oats",
      "Salt"
    ],
    "decoys": [
      "Jordan almonds",
      "Cinnamon",
      "Salmon",
      "Egg slightly beaten",
      "Almond extract",
      "Pearl tapioca"
    ],
    "steps": [
      "Beat egg until light, add gradually sugar, and then stir in remaining ingredients",
      "Drop mixture by teaspoonfuls on a thoroughly greased inverted dripping-pan one inch apart",
      "Spread into circular shape with a case knife first dipped in cold water",
      "Bake in a moderate oven until delicately browned",
      "To give variety use two-thirds cup rolled oats and fill cup with shredded cocoanut"
    ]
  },
  {
    "id": "stage-73",
    "name": "Stage 73: Chocolate Cookies",
    "recipeName": "Chocolate Cookies",
    "ingredients": [
      "Butter",
      "Sugar",
      "Egg",
      "Salt",
      "Baker’s chocolate",
      "Flour",
      "Baking powder"
    ],
    "decoys": [
      "Currants mixed with",
      "Cold boiled halibut",
      "Macaroni",
      "Carrot",
      "Brown Stock",
      "Washed figs"
    ],
    "steps": [
      "Cream the butter, add sugar gradually, egg well beaten, salt, and chocolate melted",
      "Beat well, and add flour mixed and sifted with baking powder alternately with milk",
      "Chill, roll very thin, then shape with a small cutter, first dipped in flour, and bake in a moderate oven"
    ]
  },
  {
    "id": "stage-74",
    "name": "Stage 74: Walnut Cake",
    "recipeName": "Walnut Cake",
    "ingredients": [
      "Butter",
      "Sugar",
      "Egg yolks",
      "Milk",
      "Flour",
      "Baking powder",
      "Egg whites"
    ],
    "decoys": [
      "Strawberries",
      "Fresh stewed tomatoes",
      "Marshmallows",
      "Box gelatine (scant) or",
      "Tomatoes",
      "Kumquat juice"
    ],
    "steps": [
      "Mix ingredients in order given",
      "Bake forty-five minutes in a moderate oven",
      "Cover with White Mountain Cream, crease in squares, and put one-half walnut on each square"
    ]
  },
  {
    "id": "stage-75",
    "name": "Stage 75: Eggs à la Caracas",
    "recipeName": "Eggs à la Caracas",
    "ingredients": [
      "Smoked dried beef",
      "Tomatoes",
      "Grated cheese",
      "Few drops onion juice",
      "Few grains cinnamon",
      "Few grains cayenne",
      "Butter"
    ],
    "decoys": [
      "Rye meal",
      "Fine stale bread crumbs",
      "Bananas sliced",
      "Chicken stock",
      "Cayenne",
      "Egg yolks"
    ],
    "steps": [
      "Pick over beef and chop finely, add tomatoes, cheese, onion juice, cinnamon, and cayenne",
      "Melt butter, add mixture, and when heated, add eggs well beaten",
      "Cook until eggs are of creamy consistency, stirring and scraping from bottom of pan"
    ]
  },
  {
    "id": "stage-76",
    "name": "Stage 76: Minced Mutton",
    "recipeName": "Minced Mutton",
    "ingredients": [
      "Chopped cooked mutton",
      "Egg yolks",
      "Mixed mustard",
      "Salt",
      "Cayenne",
      "Cream"
    ],
    "decoys": [
      "Almond extract",
      "Molasses",
      "Orange juice",
      "Cream or milk",
      "Cold boiled halibut",
      "Grated cheese",
      "Few grains salt"
    ],
    "steps": [
      "Mash the yolks, and season with mustard, salt, and cayenne",
      "Add cream and mutton",
      "When thoroughly heated add wine",
      "Serve on toast"
    ]
  },
  {
    "id": "stage-77",
    "name": "Stage 77: Raised Hominy Muffins",
    "recipeName": "Raised Hominy Muffins",
    "ingredients": [
      "Warm cooked hominy",
      "Butter",
      "Scalded milk",
      "Sugar",
      "Salt",
      "Yeast cake",
      "Lukewarm water"
    ],
    "decoys": [
      "Rum",
      "Rice",
      "Soft maple sugar",
      "Thick White Sauce",
      "Finely chopped chives",
      "Vanilla",
      "Sliced onions"
    ],
    "steps": [
      "Mix first five ingredients; when lukewarm add yeast cake, dissolved in lukewarm water and flour",
      "Cover, and let rise over night",
      "In the morning cut down, fill hot buttered gem pans two-thirds full, let rise one hour, and bake in a moderate oven",
      "Unless cooked hominy is rather stiff more flour will be needed"
    ]
  },
  {
    "id": "stage-78",
    "name": "Stage 78: Egg Soufflé",
    "recipeName": "Egg Soufflé",
    "ingredients": [
      "Butter",
      "Flour",
      "Milk",
      "Cream",
      "Eggs",
      "Salt"
    ],
    "decoys": [
      "Fresh stewed tomatoes",
      "Few grains pepper",
      "Whole eggs",
      "Shredded cocoanut",
      "Grated rind  orange",
      "Washed figs",
      "Shortening"
    ],
    "steps": [
      "Cream the butter, add flour, and pour on gradually scalded milk and cream",
      "Cook in double boiler five minutes, and add yolks of eggs, beaten until thick and lemon-colored",
      "Remove from fire, add seasonings, and fold in whites of eggs beaten until stiff and dry",
      "Turn into a buttered dish, or buttered individual moulds, set in pan of hot water, and bake in a slow oven until firm",
      "Egg Soufflé may be served with White Sauce I, highly seasoned with celery salt, paprika, and onion juice"
    ]
  },
  {
    "id": "stage-79",
    "name": "Stage 79: Corn Soup",
    "recipeName": "Corn Soup",
    "ingredients": [
      "Corn",
      "Boiling water",
      "Milk",
      "Onion",
      "Butter",
      "Flour",
      "Salt"
    ],
    "decoys": [
      "Ginger",
      "Marshmallows",
      "Fine stale bread crumbs",
      "Highly seasoned",
      "Macaroni",
      "Clams",
      "Cream of tartar"
    ],
    "steps": [
      "Chop the corn, add water, and simmer twenty minutes; rub through a sieve",
      "Scald milk with onion, remove onion, and add milk to corn",
      "Bind with butter and flour cooked together",
      "Add salt and pepper"
    ]
  },
  {
    "id": "stage-80",
    "name": "Stage 80: Brown Sauce II (Espagnole)",
    "recipeName": "Brown Sauce II (Espagnole)",
    "ingredients": [
      "Butter",
      "Carrot",
      "Onion",
      "Bay leaf",
      "Thyme",
      "Parsley",
      "Peppercorns",
      "Flour",
      "Brown Stock"
    ],
    "decoys": [
      "Mixed mustard",
      "Brown sugar",
      "Chopped parsley",
      "Whole eggs",
      "Fine stale bread crumbs",
      "Egg whites",
      "Washed figs"
    ],
    "steps": [
      "Cook butter with carrot, onion, bay leaf, thyme, parsley, and peppercorns, until brown, stirring constantly, care being taken that butter is not allowed to burn; add flour, and when well browned, add stock gradually",
      "Bring to boiling-point, strain, and season with salt and pepper"
    ]
  },
  {
    "id": "stage-81",
    "name": "Stage 81: Kumquat Jelly",
    "recipeName": "Kumquat Jelly",
    "ingredients": [
      "Kumquat juice",
      "Sugar",
      "Sauterne",
      "Orange Curaçoa",
      "Granulated gelatine",
      "Cold water"
    ],
    "decoys": [
      "Bananas sliced",
      "Shredded almonds",
      "Sugar or",
      "Marrowfat peas",
      "Salt and pepper",
      "Extract lemon or",
      "Arrowroot"
    ],
    "steps": [
      "Wipe three-fourths box kumquats, cut in slices, add cold water to cover, bring slowly to boiling-point, and cook slowly one-half hour; then strain; there should be one and one-half cups juice",
      "Add sugar, wine, and curaçoa",
      "Soak gelatine in cold water, and add to first mixture heated to boiling-point; then add salt",
      "Strain, turn into individual mould, and chill",
      "Remove to serving dish, and garnish with halves of kumquats, cooked in syrup until soft, drained, and rolled in sugar"
    ]
  },
  {
    "id": "stage-82",
    "name": "Stage 82: Burnt Walnut Bisque",
    "recipeName": "Burnt Walnut Bisque",
    "ingredients": [
      "Scalded milk",
      "Egg yolks",
      "Sugar",
      "Chopped walnut meats",
      "Heavy cream",
      "Vanilla"
    ],
    "decoys": [
      "Oysters",
      "Washed figs",
      "Cream",
      "Canton ginger",
      "Brown Stock",
      "Baking power",
      "Flour"
    ],
    "steps": [
      "Make custard of milk, eggs, one-third of the sugar, and salt",
      "Caramelize remaining sugar, add nut meats, and turn into a slightly buttered pan",
      "Cool, pound, and pass through a purée strainer",
      "Add to custard, cool, then add one cup heavy cream, beaten until stiff, and vanilla",
      "Freeze and mould"
    ]
  },
  {
    "id": "stage-83",
    "name": "Stage 83: Orange Delicious",
    "recipeName": "Orange Delicious",
    "ingredients": [
      "Sugar",
      "Water",
      "Orange juice",
      "Cream",
      "Yolks two eggs",
      "Heavy cream"
    ],
    "decoys": [
      "Porto Rico molasses",
      "Grated rind  orange",
      "Clove",
      "Figs, finely chopped",
      "Shredded pineapple",
      "Rolled Oats",
      "Grated mild cheese"
    ],
    "steps": [
      "Boil sugar and water eight minutes, then add orange juice",
      "Scald cream, add yolks of eggs, and cook over hot water until mixture thickens",
      "Cool, add to first mixture with heavy cream beaten stiff",
      "Freeze; when nearly frozen, add orange peel",
      "Line a melon mould with Orange Ice, fill with Orange Delicious, pack in salt and ice, and let stand one and one-half hours"
    ]
  },
  {
    "id": "stage-84",
    "name": "Stage 84: Cambridge Gingerbread",
    "recipeName": "Cambridge Gingerbread",
    "ingredients": [
      "Butter",
      "Boiling water",
      "Molasses",
      "Egg",
      "Flour",
      "Soda",
      "Salt",
      "Cinnamon",
      "Ginger"
    ],
    "decoys": [
      "Peaches",
      "Cold cooked oatmeal",
      "Onions",
      "White Sauce II",
      "Marshmallows",
      "Whites two eggs",
      "Grated nutmeg"
    ],
    "steps": [
      "Melt butter in water, add molasses, egg well beaten, and dry ingredients mixed and sifted",
      "Bake in a buttered shallow pan"
    ]
  },
  {
    "id": "stage-85",
    "name": "Stage 85: Ginger Snaps",
    "recipeName": "Ginger Snaps",
    "ingredients": [
      "Molasses",
      "Shortening",
      "Flour",
      "Soda",
      "Ginger"
    ],
    "decoys": [
      "Velouté Sauce",
      "Sliced apples",
      "Cold milk",
      "Indian meal",
      "Granulated gelatine",
      "Yvette Cordial",
      "Cinnamon"
    ],
    "steps": [
      "Heat molasses to boiling-point and pour over shortening",
      "Add dry ingredients mixed and sifted",
      "Toss one-fourth of mixture on a floured board and roll as thinly as possible; shape with a small round cutter, first dipped in flour",
      "Place near together on a buttered sheet and bake in a moderate oven",
      "Gather up the trimmings and roll with another portion of dough",
      "During rolling, the bowl containing mixture should be kept in a cool place, or it will be necessary to add more flour to dough, which makes cookies hard rather than crisp and short"
    ]
  },
  {
    "id": "stage-86",
    "name": "Stage 86: Cream Cake",
    "recipeName": "Cream Cake",
    "ingredients": [
      "Eggs",
      "Sugar",
      "Thin cream",
      "Flour",
      "Baking powder",
      "Salt",
      "Cinnamon",
      "Mace"
    ],
    "decoys": [
      "Potatoes",
      "Lukewarm water",
      "Chopped beef",
      "Soft butter",
      "French chestnuts",
      "Cold flaked salmon",
      "Wine"
    ],
    "steps": [
      "Put unbeaten eggs in a bowl, add sugar and cream, and beat vigorously",
      "Mix and sift remaining ingredients, then add to first mixture",
      "Bake thirty minutes in a shallow cake pan"
    ]
  },
  {
    "id": "stage-87",
    "name": "Stage 87: Chocolate Sponge",
    "recipeName": "Chocolate Sponge",
    "ingredients": [
      "Butter",
      "Prepared powdered cocoa",
      "Eggs",
      "Sugar",
      "Cinnamon",
      "Clove",
      "Cold water",
      "Flour"
    ],
    "decoys": [
      "Ground coffee",
      "Cloves",
      "Thick White Sauce",
      "Sliced onions",
      "Scalded milk",
      "Few grains cayenne",
      "Finely chopped parsley"
    ],
    "steps": [
      "Cream the butter; add cocoa, yolks of eggs well beaten, sugar mixed with cinnamon and clove, and water",
      "Beat the whites of eggs, and add to first mixture alternately with flour mixed and sifted with baking powder",
      "Bake in small tins from fifteen to twenty minutes"
    ]
  },
  {
    "id": "stage-88",
    "name": "Stage 88: Lobster à la Delmonico",
    "recipeName": "Lobster à la Delmonico",
    "ingredients": [
      "Lobster",
      "Butter",
      "Flour",
      "Salt",
      "Few grains cayenne",
      "Slight grating nutmeg",
      "Thin cream",
      "Egg yolks"
    ],
    "decoys": [
      "Water",
      "White corn meal",
      "Fine oatmeal",
      "Grated horseradish",
      "Paprika",
      "Pounded cardamon seeds",
      "Ginger"
    ],
    "steps": [
      "Remove lobster meat from shell and cut in small cubes",
      "Melt butter, add flour, seasonings, and cream gradually",
      "Add lobster, and when heated, add egg yolks and wine"
    ]
  },
  {
    "id": "stage-89",
    "name": "Stage 89: Pea Soup",
    "recipeName": "Pea Soup",
    "ingredients": [
      "Marrowfat peas",
      "Sugar",
      "Cold water",
      "Milk",
      "Onion",
      "Butter",
      "Flour",
      "Salt"
    ],
    "decoys": [
      "Jordan almonds",
      "Rye meal",
      "Seeded raisins",
      "White Sauce II",
      "Molasses",
      "Indian meal",
      "Madeira wine"
    ],
    "steps": [
      "Drain peas from their liquor, add sugar and cold water, and simmer twenty minutes",
      "Rub through a sieve, reheat, and thicken with butter and flour cooked together",
      "Scald milk with onion, remove onion, and add milk to pea mixture, season with salt and pepper",
      "Peas too old to serve as a vegetable may be utilized for soups"
    ]
  },
  {
    "id": "stage-90",
    "name": "Stage 90: Washington Terrapin",
    "recipeName": "Washington Terrapin",
    "ingredients": [
      "Terrapin",
      "Butter",
      "Flour",
      "Cream",
      "Chopped mushrooms",
      "Salt",
      "Few grains cayenne",
      "Eggs"
    ],
    "decoys": [
      "Yeast cakes",
      "Sherry or Madeira wine",
      "Hot liquid",
      "Lobster",
      "Grated nutmeg",
      "Graham flour",
      "Cranberries"
    ],
    "steps": [
      "Melt the butter, add flour, and pour on slowly the cream",
      "Add terrapin meat with bones cut in pieces, entrails cut smaller, liver separated in pieces, eggs of terrapin, and mushrooms",
      "Season with salt and cayenne",
      "Just before serving, add eggs slightly beaten and two tablespoons Sherry wine"
    ]
  },
  {
    "id": "stage-91",
    "name": "Stage 91: Cherry Fritters",
    "recipeName": "Cherry Fritters",
    "ingredients": [
      "Scalded milk",
      "Corn-starch",
      "Flour",
      "Sugar",
      "Salt",
      "Cold milk",
      "Egg yolks"
    ],
    "decoys": [
      "Chicken stock",
      "Prepared powdered cocoa",
      "Yeast cake dissolved in",
      "Parsley",
      "Shredded cocoanut",
      "Whole eggs",
      "Finely chopped parsley"
    ],
    "steps": [
      "Mix corn-starch, flour, sugar, and salt",
      "Dilute with cold milk and add beaten yolks; then add gradually to scalded milk and cook fifteen minutes in double boiler",
      "Add cherries, pour into a buttered shallow tin, and cool",
      "Turn on a board, cut in squares, dip in flour, egg, and crumbs, fry in deep fat, and drain",
      "Serve with Maraschino Sauce"
    ]
  },
  {
    "id": "stage-92",
    "name": "Stage 92: Mock Crabs",
    "recipeName": "Mock Crabs",
    "ingredients": [
      "Butter",
      "Flour",
      "Salt",
      "Mustard",
      "Paprika",
      "Scalded milk",
      "Kornlet",
      "Egg",
      "Worcestershire Sauce"
    ],
    "decoys": [
      "Mace",
      "Warm wheat mush",
      "Granulated gelatin",
      "Rye flour",
      "Porto Rico molasses",
      "Chopped lobster meat",
      "Pearl tapioca",
      "Chicken stock"
    ],
    "steps": [
      "Melt butter, add flour mixed with dry seasonings, and pour on gradually the milk",
      "Add Kornlet, egg slightly beaten, and Worcestershire Sauce",
      "Pour into a buttered baking-dish, cover with crumbs, and bake until crumbs are brown"
    ]
  },
  {
    "id": "stage-93",
    "name": "Stage 93: Macaroon Cream",
    "recipeName": "Macaroon Cream",
    "ingredients": [
      "Box gelatine or",
      "Granulated gelatine",
      "Cold water",
      "Scalded milk",
      "Egg yolks",
      "Sugar",
      "Salt",
      "Pounded macaroons",
      "Vanilla"
    ],
    "decoys": [
      "Lukewarm water",
      "Marshmallows",
      "Washed figs",
      "Shrimps",
      "Chopped walnut meats",
      "Dried lima beans",
      "Hot liquid",
      "Cabbage"
    ],
    "steps": [
      "Soak gelatine in cold water",
      "Make custard of milk, yolks of eggs, sugar, and salt; add gelatine, and strain into pan set in ice-water",
      "Add macaroons and flavoring, stirring until it begins to thicken; then add whites of eggs beaten stiff, mould, chill, and serve garnished with macaroons"
    ]
  },
  {
    "id": "stage-94",
    "name": "Stage 94: Jelly Jumbles",
    "recipeName": "Jelly Jumbles",
    "ingredients": [
      "Butter",
      "Sugar",
      "Egg",
      "Soda",
      "Sour milk",
      "Salt",
      "Flour"
    ],
    "decoys": [
      "Cranberries",
      "Figs, finely chopped",
      "Brandy",
      "Kumquat juice",
      "Chopped salted almonds",
      "Sauterne",
      "Rum",
      "White Stock"
    ],
    "steps": [
      "Cream the butter, add sugar gradually, egg well beaten, soda mixed with milk, salt and flour to make a soft dough",
      "Chill and shape, using a round cutter",
      "On the centres of one-half the pieces put currant jelly",
      "Make three small openings in remaining halves, using a thimble, and put pieces together",
      "Press edges slightly, and bake in a rather hot oven, that jumbles may keep in good shape"
    ]
  },
  {
    "id": "stage-95",
    "name": "Stage 95: Shrimps à la Newburg",
    "recipeName": "Shrimps à la Newburg",
    "ingredients": [
      "Shrimps",
      "Butter",
      "Salt",
      "Few grains cayenne",
      "Lemon juice",
      "Flour",
      "Cream",
      "Egg yolks"
    ],
    "decoys": [
      "Squash",
      "Rolled Oats",
      "Potatoes",
      "Salt and paprika",
      "Washed figs",
      "Extract lemon or",
      "Lukewarm water",
      "Egg well beaten"
    ],
    "steps": [
      "Clean shrimps and cook three minutes in two tablespoons butter",
      "Add salt, cayenne, and lemon juice, and cook one minute",
      "Remove shrimps, and put remaining butter in chafing-dish, add flour and cream; when thickened, add yolks of eggs slightly beaten, shrimps, and wine",
      "Serve with toast or Puff Paste Points"
    ]
  },
  {
    "id": "stage-96",
    "name": "Stage 96: Split Pea Soup",
    "recipeName": "Split Pea Soup",
    "ingredients": [
      "Dried split peas",
      "Cold water",
      "Milk",
      "Onion",
      "Butter",
      "Flour",
      "Salt",
      "Pepper"
    ],
    "decoys": [
      "Chopped parsley",
      "Cream of tartar",
      "Vinegar",
      "Onions",
      "Granulated gelatin",
      "Beef extract",
      "White one egg",
      "Egg well beaten"
    ],
    "steps": [
      "Pick over peas and soak several hours, drain, add cold water, pork, and onion",
      "Simmer three or four hours, or until soft; rub through a sieve",
      "Add butter and flour cooked together, salt, and pepper",
      "Dilute with milk, adding more if necessary",
      "The water in which a ham has been cooked may be used; in such case omit salt"
    ]
  },
  {
    "id": "stage-97",
    "name": "Stage 97: Oysters à la D’Uxelles",
    "recipeName": "Oysters à la D’Uxelles",
    "ingredients": [
      "Oysters",
      "Chopped mushrooms",
      "Butter",
      "Flour",
      "Salt",
      "Lemon juice",
      "Few grains cayenne",
      "Egg yolk"
    ],
    "decoys": [
      "Prepared powdered cocoa",
      "Milk",
      "Yolks two eggs",
      "Green Coloring",
      "Box strawberries",
      "Cold milk",
      "Vanilla",
      "Melted butter"
    ],
    "steps": [
      "Clean oysters, heat to boiling-point, and drain",
      "Reserve liquor and strain through double thickness of cheese-cloth; there should be three-fourths cup",
      "Cook butter and mushrooms five minutes, add flour, and oyster liquor gradually; then cook three minutes",
      "Add seasonings, oysters, egg, and Sherry wine",
      "Serve on zephyrettes or pieces of toasted bread"
    ]
  },
  {
    "id": "stage-98",
    "name": "Stage 98: Coffee Cakes (Brioche)",
    "recipeName": "Coffee Cakes (Brioche)",
    "ingredients": [
      "Scalded milk",
      "Yolks of eggs",
      "Whole eggs",
      "Butter",
      "Sugar",
      "Yeast cakes",
      "Extract lemon or",
      "Pounded cardamon seeds",
      "Flour"
    ],
    "decoys": [
      "Heavy cream",
      "Oranges",
      "Highly seasoned",
      "Fine oatmeal",
      "Mustard",
      "Washed figs",
      "Coffee infusion",
      "Rye meal"
    ],
    "steps": [
      "Cool milk; when lukewarm, add yeast cakes, and when they are dissolved add remaining ingredients, and beat thoroughly with hand ten minutes; let rise six hours",
      "Keep in ice-box over night; in morning turn on floured board, roll in long rectangular piece one-fourth inch thick; spread with softened butter, fold from sides toward centre to make three layers",
      "Cut off pieces three-fourths inch wide; cover and let rise",
      "Take each piece separately in hands and twist from ends in opposite directions, coil and bring ends together at top of cake",
      "Let rise in pans and bake twenty minutes in a moderate oven; cool and brush over with confectioners’ sugar, moistened with boiling water to spread, and flavored with vanilla"
    ]
  },
  {
    "id": "stage-99",
    "name": "Stage 99: Chocolate Rice Meringue",
    "recipeName": "Chocolate Rice Meringue",
    "ingredients": [
      "Milk",
      "Rice",
      "Salt",
      "Butter",
      "Sugar",
      "Square melted chocolate",
      "Vanilla",
      "Seeded raisins",
      "Whites two eggs"
    ],
    "decoys": [
      "Egg well beaten",
      "Sauterne",
      "Cream of tartar",
      "White Sauce II",
      "Ice",
      "Currants mixed with",
      "Corn-starch",
      "Egg slightly beaten"
    ],
    "steps": [
      "Scald milk, add rice and salt, and cook until rice is soft",
      "Add butter, sugar, chocolate, vanilla, and raisins",
      "Cut and fold in the whites of eggs, beaten until stiff, and cream, beaten until stiff",
      "Pour into a buttered baking-dish, and bake fifteen minutes",
      "Cover with a meringue made of the whites of three eggs, six tablespoons powdered sugar, and one-half teaspoon vanilla; then brown in a moderate oven"
    ]
  },
  {
    "id": "stage-100",
    "name": "Stage 100: Junket Ice Cream with Peaches",
    "recipeName": "Junket Ice Cream with Peaches",
    "ingredients": [
      "Lukewarm milk",
      "Heavy cream",
      "Sugar",
      "Salt",
      "Junket Tablets",
      "Cold water",
      "Vanilla",
      "Almond extract",
      "Green Coloring"
    ],
    "decoys": [
      "Finely chopped chives",
      "Sherry",
      "Chestnut purée",
      "Hot water",
      "Graham flour",
      "Sugar or",
      "Shrimps",
      "Fine oatmeal"
    ],
    "steps": [
      "Mix first four ingredients, and add junket tablets dissolved in cold water",
      "Turn into a pudding-dish and let stand until set",
      "Add flavoring and coloring",
      "Freeze, mould, and serve garnished with halves of peaches, filling cavities with halves of blanched almonds",
      "Turn peaches into a saucepan, add one-third cup sugar, and cook slowly until syrup is thick",
      "Cool before garnishing ice cream"
    ]
  }
];
})(typeof self !== "undefined" ? self : this);
